const logo =
  "https://privilegia.uz/wp-content/uploads/2022/06/m126334-0027-e1655211784911.png";

const getRandomPrice = () => {
  return Math.floor(Math.random() * (10000 - 1000 + 1)) + 1000; // Random price between 1000 and 10000
};
export const images = [
  { logo, id: 1 },
  { logo, id: 2 },
  { logo, id: 3 },
];
export let homeData = [
  {
    id: 1,
    image: logo,
    description: "Multicolored armless top",
    price: getRandomPrice(),
    category: "denim",
    color: "purple",
    size: "28",
    select: "best",
  },
  {
    id: 2,
    image: logo,
    description: "Grey bee wrist-watch",
    price: getRandomPrice(),
    category: "jeans",
    color: "gold",
    size: "26",
    select: "popular",
  },
  {
    id: 3,
    image: logo,
    description: "Mini skirt",
    price: getRandomPrice(),
    category: "jackets and coats",
    color: "pink",
    size: "23",
    select: "best",
  },
  {
    id: 4,
    image: logo,
    description: "Red lightweight gown",
    price: getRandomPrice(),
    category: "sweaters & knits",
    color: "red",
    size: "27",
    select: "popular",
  },
  {
    id: 5,
    image: logo,
    description: "Blue botton-down gown",
    price: getRandomPrice(),
    category: "leather",
    color: "brown",
    size: "24",
    select: "best",
  },
  {
    id: 6,
    image: logo,
    description: "Moon and star neckpiece",
    price: getRandomPrice(),
    category: "skirts",
    color: "white",
    size: "29",
    select: "popular",
  },
  {
    id: 7,
    image: logo,
    description: "Tambourine Crossbody Bag",
    price: getRandomPrice(),
    category: "jumpsuits",
    color: "taupe",
    size: "27",
    select: "best",
  },
  {
    id: 8,
    image: logo,
    description: "Katy Perry Killer Queen EDP",
    price: getRandomPrice(),
    category: "tops",
    color: "beige",
    size: "xs",
    select: "popular",
  },
  {
    id: 9,
    image: logo,
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "dresses",
    color: "brown",
    size: "xl",
    select: "best",
  },
  {
    id: 10,
    image: logo,
    description: "Nerdy oval glasses",
    price: getRandomPrice(),
    category: "tops",
    color: "black",
    size: "23",
    select: "popular",
  },
  {
    id: 11,
    image: logo,
    description: "Diamond ladies ring",
    price: getRandomPrice(),
    category: "dresses",
    color: "black",
    size: "2",
    select: "best",
  },
  {
    id: 12,
    image: logo,
    description: "Ladies bush pants",
    price: getRandomPrice(),
    category: "jumpsuits",
    color: "green",
    size: "l",
    select: "popular",
  },
  {
    id: 13,
    image: logo,
    description: "Guilhermina Embellished Slides",
    price: getRandomPrice(),
    category: "jeans",
    color: "black",
    size: "xs",
    select: "best",
  },
  {
    id: 14,
    image: logo,
    description: "Superga Plaid Sneakers",
    price: getRandomPrice(),
    category: "denim",
    color: "blue",
    size: "s",
    select: "popular",
  },
  {
    id: 15,
    image: logo,
    description: "Checked ladies trouser",
    price: getRandomPrice(),
    category: "dresses",
    color: "red",
    size: "m",
    select: "best",
  },
  {
    id: 16,
    image: logo,
    description: "Beanie winter fleece",
    price: getRandomPrice(),
    category: "pants",
    color: "pink",
    size: "xxs",
    select: "popular",
  },
  {
    id: 17,
    image: logo,
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "loungerie & underwear",
    color: "white",
    size: "29",
    select: "best",
  },
  {
    id: 18,
    image: logo,
    description: "Red lightweight gown",
    price: getRandomPrice(),
    category: "skirts",
    color: "taupe",
    size: "27",
    select: "popular",
  },
  {
    id: 19,
    image: logo,
    description: "Moon and star neckpiece",
    price: getRandomPrice(),
    category: "shorts",
    color: "gold",
    size: "27",
    select: "best",
  },
  {
    id: 20,
    image: logo,
    description: "Grey bee wrist-watch",
    price: getRandomPrice(),
    category: "pants",
    color: "purple",
    size: "26",
    select: "popular",
  },
  {
    id: 21,
    image: logo,
    description: "Katy Perry Killer Queen EDP",
    price: getRandomPrice(),
    category: "jackets and coats",
    color: "brown",
    size: "25",
    select: "best",
  },
  {
    id: 22,
    image: logo,
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "tops ",
    color: "green",
    size: "29",
    select: "popular",
  },
  {
    id: 23,
    image: logo,
    description: "Nerdy oval glasses",
    price: getRandomPrice(),
    category: "jumpsuits",
    color: "orange",
    size: "30",
    select: "best",
  },
  {
    id: 24,
    image: logo,
    description: "Katy Perry Killer Queen EDP",
    price: getRandomPrice(),
    category: "jeans",
    color: "blue",
    size: "32",
    select: "popular",
  },
  {
    id: 25,
    image: logo,
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "denim ",
    color: "black",
    size: "31",
    select: "best",
  },
  {
    id: 26,
    image: logo,
    description: "Nerdy oval glasses",
    price: getRandomPrice(),
    category: "dresses",
    color: "belge",
    size: "32",
    select: "popular",
  },
];

export let shoesData = [
  {
    id: 27,
    image: logo,
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    type: "boots",
    size: "40/7.5",
    color: "green",
    select: "priceLowToHigh",
  },
  {
    id: 28,
    image: logo,
    description: "Keds sneakers",
    price: getRandomPrice(),
    type: "sneakers",
    size: "35.5/5",
    color: "gold",
    select: "priceHighToLow",
  },
  {
    id: 29,
    image: logo,
    description: "Guilhermina Embellished Slides",
    price: getRandomPrice(),
    type: "sandals",
    size: "41.5/10",
    color: "orange",
    select: "priceLowToHigh",
  },
  {
    id: 30,
    image: logo,
    description: "Summer shoes",
    price: getRandomPrice(),
    type: "heels",
    size: "41/9.5",
    color: "blue",
    select: "priceHighToLow",
  },
  {
    id: 31,
    image: logo,
    description: "Casual Flat Loafers",
    price: getRandomPrice(),
    type: "oxfords",
    size: "43/12",
    color: "taupe",
    select: "priceLowToHigh",
  },
  {
    id: 32,
    image: logo,
    description: "Black strappy peeptoe",
    price: getRandomPrice(),
    type: "booties",
    size: "41/9.5",
    color: "belge",
    select: "priceHighToLow",
  },
  {
    id: 33,
    image: logo,
    description: "Superga Platform Sneakers",
    price: getRandomPrice(),
    type: "sneakers",
    size: "39/7.5",
    color: "red",
    select: "priceLowToHigh",
  },
  {
    id: 34,
    image: logo,
    description: "Heeled sandals",
    price: getRandomPrice(),
    type: "slides",
    size: "39.5/8",
    color: "purple",
    select: "priceHighToLow",
  },
  {
    id: 35,
    image: logo,
    description: "HAJINK Boat Shoes",
    price: getRandomPrice(),
    type: "mules",
    size: "36/5.5",
    color: "pink",
    select: "priceLowToHigh",
  },
  {
    id: 36,
    image: logo,
    description: "Casual Flat Sandals",
    price: getRandomPrice(),
    type: "sandals",
    size: "42/11",
    color: "white",
    select: "priceHighToLow",
  },
  {
    id: 37,
    image: logo,
    description: "Summer Cork Slippers",
    price: getRandomPrice(),
    type: "slippers",
    size: "37.5/6.5",
    color: "brown",
    select: "priceLowToHigh",
  },
  {
    id: 38,
    image: logo,
    description: "Ankle boots",
    price: getRandomPrice(),
    type: "wedges",
    size: "42/10.5",
    color: "brown",
    select: "priceHighToLow",
  },
  {
    id: 39,
    image: logo,
    description: "Summer shoes",
    price: getRandomPrice(),
    type: "vegan",
    size: "39/7.5",
    color: "gold",
    select: "priceLowToHigh",
  },
  {
    id: 40,
    image: logo,
    description: "Casual Flat Loafers",
    price: getRandomPrice(),
    type: "party",
    size: "40/7.5",
    color: "black",
    select: "priceHighToLow",
  },
];

export let accessoriesData = [
  {
    id: 42,
    image: logo,
    description: "Tambourine Crossbody Bag",
    price: getRandomPrice(),
    type: "handbag",
    color: "green",
    size: "m",
    select: "popular",
  },
  {
    id: 43,
    image: logo,
    description: "Summer Handbag",
    price: getRandomPrice(),
    type: "handbag",
    color: "pink",
    size: "m",
    select: "best",
  },
  {
    id: 44,
    image: logo,
    description: "Nereide Oval",
    price: getRandomPrice(),
    type: "sunglasses & eyewears",
    color: "white",
    size: "m",
    select: "popular",
  },
  {
    id: 45,
    image: logo,
    description: "Diamond ladies ring",
    price: getRandomPrice(),
    type: "jewelry",
    color: "gold",
    size: "m",
    select: "best",
  },
  {
    id: 46,
    image: logo,
    description: "Casual baseball cap",
    price: getRandomPrice(),
    type: "hats",
    color: "red",
    size: "m",
    select: "popular",
  },
  {
    id: 47,
    image: logo,
    description: "Tear-drop stone necklace",
    price: getRandomPrice(),
    type: "jewelry",
    color: "blue",
    size: "m",
    select: "best",
  },
  {
    id: 48,
    image: logo,
    description: "Ladies luxury watch",
    price: getRandomPrice(),
    type: "watch",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 49,
    image: logo,
    description: "Heeled sandals",
    price: getRandomPrice(),
    type: "sock",
    color: "blue",
    size: "m",
    select: "best",
  },
  {
    id: 50,
    image: logo,
    description: "Pattern Cloth Face Mask",
    price: getRandomPrice(),
    type: "watch",
    color: "black",
    size: "m",
    select: "popular",
  },
  {
    id: 51,
    image: logo,
    description: "Fashion ladies watch",
    price: getRandomPrice(),
    type: "watch",
    color: "black",
    size: "m",
    select: "best",
  },
  {
    id: 52,
    image: logo,
    description: "Beanie winter fleece",
    price: getRandomPrice(),
    type: "sock",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 53,
    image: logo,
    description: "Black ladies backpack",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "best",
  },
  {
    id: 54,
    image: logo,
    description: "Pattern Cloth Face Mask",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 55,
    image: logo,
    description: "Fashion ladies watch",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "best",
  },
  {
    id: 56,
    image: logo,
    description: "Casual baseball cap",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 57,
    image: logo,
    description: "Tear-drop stone necklace",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "best",
  },
];

export const allData = [...homeData, ...shoesData, ...accessoriesData];
