const logo =
  "https://privilegia.uz/wp-content/uploads/2022/06/m126334-0027-e1655211784911.png";

const getRandomPrice = () => {
  return Math.floor(Math.random() * (10000 - 1000 + 1)) + 1000; // Random price between 1000 and 10000
};
import sliderImg from "./constants/opa.jpg";
export const images = [
  { logo: sliderImg, id: 1 },
  { logo: sliderImg, id: 2 },
  { logo: sliderImg, id: 3 },
];
export let homeData = [
  {
    id: 1,
    image:
      "https://cdn-images.farfetch-contents.com/18/91/46/06/18914606_41214467_1000.jpg",
    description: "Multicolored armless top",
    price: getRandomPrice(),
    category: "denim",
    color: "purple",
    size: "28",
    select: "best",
  },
  {
    id: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzs6dxJ0rRA023FH5UH1mEPejruAR_aRETSg&usqp=CAU",
    description: "Grey bee wrist-watch",
    price: getRandomPrice(),
    category: "jeans",
    color: "gold",
    size: "26",
    select: "popular",
  },
  {
    id: 3,
    image:
      "https://www.bodenimages.com/productimages/r1aproductlarge/23waut_r0441_blk.jpg",
    description: "Mini skirt",
    price: getRandomPrice(),
    category: "jackets and coats",
    color: "pink",
    size: "23",
    select: "best",
  },
  {
    id: 4,
    image:
      "https://bdci.imgix.net/i/8cfefd69_bd22br03-22_red_1.jpg?fit=fill&w=500&h=500&bg=fff&q=90&nrs=80&x=1",
    description: "Red lightweight gown",
    price: getRandomPrice(),
    category: "sweaters & knits",
    color: "red",
    size: "27",
    select: "popular",
  },
  {
    id: 5,
    image:
      "https://res.cloudinary.com/wolfandbadger/image/upload/f_auto,q_auto:best,c_pad,h_800,w_800/products/floral-button-down-maxi-dress-blue__389ed968670c430b0b5029f0c69b5ec2",
    description: "Blue botton-down gown",
    price: getRandomPrice(),
    category: "leather",
    color: "brown",
    size: "24",
    select: "best",
  },
  {
    id: 6,
    image:
      "https://slimages.macysassets.com/is/image/MCY/products/3/optimized/19553333_fpx.tif?$browse$&wid=178&fmt=jpeg",
    description: "Moon and star neckpiece",
    price: getRandomPrice(),
    category: "skirts",
    color: "white",
    size: "29",
    select: "popular",
  },
  {
    id: 7,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRUo8wjSJE4rraZqPVNDZO1WxNdTb8EuBS8g&usqp=CAU",
    description: "Tambourine Crossbody Bag",
    price: getRandomPrice(),
    category: "jumpsuits",
    color: "taupe",
    size: "27",
    select: "best",
  },
  {
    id: 8,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg2ALrmVdY_ov9tbaxoX9oEHM01QCi7YDJqQ&usqp=CAU",
    description: "Katy Perry Killer Queen EDP",
    price: getRandomPrice(),
    category: "tops",
    color: "beige",
    size: "xs",
    select: "popular",
  },
  {
    id: 9,
    image:
      "https://cdn4.vectorstock.com/i/1000x1000/33/98/woman-fashion-shoes-on-high-heels-vector-4753398.jpg",
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "dresses",
    color: "brown",
    size: "xl",
    select: "best",
  },
  {
    id: 10,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy-hiJ1Iu2fk7KnfqS0SNoYxuQWZ9crKUUyw&usqp=CAU",
    description: "Nerdy oval glasses",
    price: getRandomPrice(),
    category: "tops",
    color: "black",
    size: "23",
    select: "popular",
  },
  {
    id: 11,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7BpuSH3IvYBZ-mNfW-1IaVVUu7Sji-MRDjA&usqp=CAU",
    description: "Diamond ladies ring",
    price: getRandomPrice(),
    category: "dresses",
    color: "black",
    size: "2",
    select: "best",
  },
  {
    id: 12,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa5NrFXcgdeJeL6oMV8Aq2LoWeqBCajsjM2Q&usqp=CAU",
    description: "Ladies bush pants",
    price: getRandomPrice(),
    category: "jumpsuits",
    color: "green",
    size: "l",
    select: "popular",
  },
  {
    id: 13,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvQ1c2vD4AB52Hy8D8P4xemoZbe4GJiwj54g&usqp=CAU",
    description: "Guilhermina Embellished Slides",
    price: getRandomPrice(),
    category: "jeans",
    color: "black",
    size: "xs",
    select: "best",
  },
  {
    id: 14,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSigcmALwDd2g0916xVuSWRVZLTcXZe-VnA1g&usqp=CAU",
    description: "Superga Plaid Sneakers",
    price: getRandomPrice(),
    category: "denim",
    color: "blue",
    size: "s",
    select: "popular",
  },
  {
    id: 15,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIqqhVWVoDEBdH4rbIlS3yCUGGqRDfQ5QTIw&usqp=CAU",
    description: "Checked ladies trouser",
    price: getRandomPrice(),
    category: "dresses",
    color: "red",
    size: "m",
    select: "best",
  },
  {
    id: 16,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo-4CMqoRwn4zZdAUKK6Uik3nSJnuxhttUXw&usqp=CAU",
    description: "Beanie winter fleece",
    price: getRandomPrice(),
    category: "pants",
    color: "pink",
    size: "xxs",
    select: "popular",
  },
  {
    id: 17,
    image:
      "https://cdn4.vectorstock.com/i/1000x1000/33/98/woman-fashion-shoes-on-high-heels-vector-4753398.jpg",
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "loungerie & underwear",
    color: "white",
    size: "29",
    select: "best",
  },
  {
    id: 18,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaj7zsk8i3iLgR38qGaUE1jvhRIXwrTlsmELehxo_wRrBPce9LtXQzTS2Mt-5smNmuqTI&usqp=CAU",
    description: "Red lightweight gown",
    price: getRandomPrice(),
    category: "skirts",
    color: "taupe",
    size: "27",
    select: "popular",
  },
  {
    id: 19,
    image: "https://slimages.macysassets.com/is/image/MCY/products/3/optimized/19553333_fpx.tif?$browse$&wid=178&fmt=jpeg",
    description: "Moon and star neckpiece",
    price: getRandomPrice(),
    category: "shorts",
    color: "gold",
    size: "27",
    select: "best",
  },
  {
    id: 20,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzs6dxJ0rRA023FH5UH1mEPejruAR_aRETSg&usqp=CAU",
    description: "Grey bee wrist-watch",
    price: getRandomPrice(),
    category: "pants",
    color: "purple",
    size: "26",
    select: "popular",
  },
  {
    id: 21,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg2ALrmVdY_ov9tbaxoX9oEHM01QCi7YDJqQ&usqp=CAU",
    description: "Katy Perry Killer Queen EDP",
    price: getRandomPrice(),
    category: "jackets and coats",
    color: "brown",
    size: "25",
    select: "best",
  },
  {
    id: 22,
    image:
      "https://cdn4.vectorstock.com/i/1000x1000/33/98/woman-fashion-shoes-on-high-heels-vector-4753398.jpg",
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "tops ",
    color: "green",
    size: "29",
    select: "popular",
  },
  {
    id: 23,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy-hiJ1Iu2fk7KnfqS0SNoYxuQWZ9crKUUyw&usqp=CAU",
    description: "Nerdy oval glasses",
    price: getRandomPrice(),
    category: "jumpsuits",
    color: "orange",
    size: "30",
    select: "best",
  },
  {
    id: 24,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg2ALrmVdY_ov9tbaxoX9oEHM01QCi7YDJqQ&usqp=CAU",
    description: "Katy Perry Killer Queen EDP",
    price: getRandomPrice(),
    category: "jeans",
    color: "blue",
    size: "32",
    select: "popular",
  },
  {
    id: 25,
    image:
      "https://cdn4.vectorstock.com/i/1000x1000/33/98/woman-fashion-shoes-on-high-heels-vector-4753398.jpg",
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    category: "denim ",
    color: "black",
    size: "31",
    select: "best",
  },
  {
    id: 26,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy-hiJ1Iu2fk7KnfqS0SNoYxuQWZ9crKUUyw&usqp=CAU",
    description: "Nerdy oval glasses",
    price: getRandomPrice(),
    category: "dresses",
    color: "belge",
    size: "32",
    select: "popular",
  },
];

export let shoesData = [
  {
    id: 27,
    image: "https://cdn4.vectorstock.com/i/1000x1000/33/98/woman-fashion-shoes-on-high-heels-vector-4753398.jpg",
    description: "High heels ladies shoes",
    price: getRandomPrice(),
    type: "boots",
    size: "40/7.5",
    color: "green",
    select: "priceLowToHigh",
  },
  {
    id: 28,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRNviAVKV-qeViBVZLV-6dguC9Z0j16r6xiA&usqp=CAU",
    description: "Keds sneakers",
    price: getRandomPrice(),
    type: "sneakers",
    size: "35.5/5",
    color: "gold",
    select: "priceHighToLow",
  },
  {
    id: 29,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvQ1c2vD4AB52Hy8D8P4xemoZbe4GJiwj54g&usqp=CAU",
    description: "Guilhermina Embellished Slides",
    price: getRandomPrice(),
    type: "sandals",
    size: "41.5/10",
    color: "orange",
    select: "priceLowToHigh",
  },
  {
    id: 30,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8JUPL6nzRgcudIh8b6Kr8ApYmSAwTwHEd2w&usqp=CAU",
    description: "Summer shoes",
    price: getRandomPrice(),
    type: "heels",
    size: "41/9.5",
    color: "blue",
    select: "priceHighToLow",
  },
  {
    id: 31,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDpivrGVq6fEic4dQ5bfOC1qkz7Ugu1OvYWA&usqp=CAU",
    description: "Casual Flat Loafers",
    price: getRandomPrice(),
    type: "oxfords",
    size: "43/12",
    color: "taupe",
    select: "priceLowToHigh",
  },
  {
    id: 32,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcgucJBo9MZyJ9EYsNWRNpE8eYuRzPQjYoOg&usqp=CAU",
    description: "Black strappy peeptoe",
    price: getRandomPrice(),
    type: "booties",
    size: "41/9.5",
    color: "belge",
    select: "priceHighToLow",
  },
  {
    id: 33,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSul4tabgRRwJ24RGy8q15wHoVt5al2Aqlh0Q&usqp=CAU",
    description: "Superga Platform Sneakers",
    price: getRandomPrice(),
    type: "sneakers",
    size: "39/7.5",
    color: "red",
    select: "priceLowToHigh",
  },
  {
    id: 34,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6CGKLQC95C6bm69O6VOect5mV2nd2UNTbJA&usqp=CAU",
    description: "Heeled sandals",
    price: getRandomPrice(),
    type: "slides",
    size: "39.5/8",
    color: "purple",
    select: "priceHighToLow",
  },
  {
    id: 35,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkDzTXN_2qIeppxezi-b4nIlTZC6sm34H0XA&usqp=CAU",
    description: "HAJINK Boat Shoes",
    price: getRandomPrice(),
    type: "mules",
    size: "36/5.5",
    color: "pink",
    select: "priceLowToHigh",
  },
  {
    id: 36,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxLMkOOSnn1bmTnyd5JPFqkL6HLMlZs6djlQ&usqp=CAU",
    description: "Casual Flat Sandals",
    price: getRandomPrice(),
    type: "sandals",
    size: "42/11",
    color: "white",
    select: "priceHighToLow",
  },
  {
    id: 37,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe-smlR4qtr10zQs4dgFCzj7nCtBS48a21KA&usqp=CAU",
    description: "Summer Cork Slippers",
    price: getRandomPrice(),
    type: "slippers",
    size: "37.5/6.5",
    color: "brown",
    select: "priceLowToHigh",
  },
  {
    id: 38,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0gor5rHLK3pV63sx594Ad4zfVrapB0_H_pg&usqp=CAU",
    description: "Ankle boots",
    price: getRandomPrice(),
    type: "wedges",
    size: "42/10.5",
    color: "brown",
    select: "priceHighToLow",
  },
  {
    id: 39,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8JUPL6nzRgcudIh8b6Kr8ApYmSAwTwHEd2w&usqp=CAU",
    description: "Summer shoes",
    price: getRandomPrice(),
    type: "vegan",
    size: "39/7.5",
    color: "gold",
    select: "priceLowToHigh",
  },
  {
    id: 40,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDpivrGVq6fEic4dQ5bfOC1qkz7Ugu1OvYWA&usqp=CAU",
    description: "Casual Flat Loafers",
    price: getRandomPrice(),
    type: "party",
    size: "40/7.5",
    color: "black",
    select: "priceHighToLow",
  },
];

export let accessoriesData = [
  {
    id: 42,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRUo8wjSJE4rraZqPVNDZO1WxNdTb8EuBS8g&usqp=CAU",
    description: "Tambourine Crossbody Bag",
    price: getRandomPrice(),
    type: "handbag",
    color: "green",
    size: "m",
    select: "popular",
  },
  {
    id: 43,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8tvEUBxL0JXicFNjq3Df3b0-UMaqbzkzaAA&usqp=CAU",
    description: "Summer Handbag",
    price: getRandomPrice(),
    type: "handbag",
    color: "pink",
    size: "m",
    select: "best",
  },
  {
    id: 44,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpfLV9kdjA_msmS9-D6rmutCQRWNCZRpOLwA&usqp=CAU",
    description: "Nereide Oval",
    price: getRandomPrice(),
    type: "sunglasses & eyewears",
    color: "white",
    size: "m",
    select: "popular",
  },
  {
    id: 45,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7BpuSH3IvYBZ-mNfW-1IaVVUu7Sji-MRDjA&usqp=CAU",
    description: "Diamond ladies ring",
    price: getRandomPrice(),
    type: "jewelry",
    color: "gold",
    size: "m",
    select: "best",
  },
  {
    id: 46,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrQoa9ZRAd5liMOmtCA5UAyV7Xk6W9ffF2Ew&usqp=CAU",
    description: "Casual baseball cap",
    price: getRandomPrice(),
    type: "hats",
    color: "red",
    size: "m",
    select: "popular",
  },
  {
    id: 47,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB3B9VNW-duc5Wxl-awRAsatUMTQijWQkv4A&usqp=CAU",
    description: "Tear-drop stone necklace",
    price: getRandomPrice(),
    type: "jewelry",
    color: "blue",
    size: "m",
    select: "best",
  },
  {
    id: 48,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzRKOnHY25USsQUKNUuzL5GAUyDPzsbALSUw&usqp=CAU",
    description: "Ladies luxury watch",
    price: getRandomPrice(),
    type: "watch",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 49,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6CGKLQC95C6bm69O6VOect5mV2nd2UNTbJA&usqp=CAU",
    description: "Heeled sandals",
    price: getRandomPrice(),
    type: "sock",
    color: "blue",
    size: "m",
    select: "best",
  },
  {
    id: 50,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuE-BB1npjCnFVPvnu1K9TOl4GIAHV_iZFOA&usqp=CAU",
    description: "Pattern Cloth Face Mask",
    price: getRandomPrice(),
    type: "watch",
    color: "black",
    size: "m",
    select: "popular",
  },
  {
    id: 51,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCnxqpEWVBtsHVXmSPSRNqsrPg97hLHxCFAA&usqp=CAU",
    description: "Fashion ladies watch",
    price: getRandomPrice(),
    type: "watch",
    color: "black",
    size: "m",
    select: "best",
  },
  {
    id: 52,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo-4CMqoRwn4zZdAUKK6Uik3nSJnuxhttUXw&usqp=CAU",
    description: "Beanie winter fleece",
    price: getRandomPrice(),
    type: "sock",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 53,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlnwg36-KmSBD_-cbvKj0UJjUA3JHkb2jf2Q&usqp=CAU",
    description: "Black ladies backpack",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "best",
  },
  {
    id: 54,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuE-BB1npjCnFVPvnu1K9TOl4GIAHV_iZFOA&usqp=CAU",
    description: "Pattern Cloth Face Mask",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 55,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCnxqpEWVBtsHVXmSPSRNqsrPg97hLHxCFAA&usqp=CAU",
    description: "Fashion ladies watch",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "best",
  },
  {
    id: 56,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrQoa9ZRAd5liMOmtCA5UAyV7Xk6W9ffF2Ew&usqp=CAU",
    description: "Casual baseball cap",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "popular",
  },
  {
    id: 57,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB3B9VNW-duc5Wxl-awRAsatUMTQijWQkv4A&usqp=CAU",
    description: "Tear-drop stone necklace",
    price: getRandomPrice(),
    type: "handbag",
    color: "brown",
    size: "m",
    select: "best",
  },
];

export const allData = [...homeData, ...shoesData, ...accessoriesData];
